[package]
name = "rocklake-node"
version = "0.63.1"
edition = "2021"
license = "Apache-2.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
rocklake-client = { path = "../../crates/rocklake-client" }
napi = { version = "2.16", features = ["napi6"] }
napi-derive = "2.16"

[build-dependencies]
napi-build = "2"

[workspace]
