#!/usr/bin/env python3
"""Validate a candidate-specific RockLake evidence report."""

from __future__ import annotations

import argparse
import json
import subprocess
from pathlib import Path


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("report", type=Path)
    parser.add_argument("--release", required=True)
    parser.add_argument("--repetitions", type=int, required=True)
    args = parser.parse_args()
    report = json.loads(args.report.read_text())

    if report["release"] != args.release:
        raise SystemExit(f"report release mismatch: {report['release']} != {args.release}")
    current_sha = subprocess.check_output(
        ["git", "rev-parse", "HEAD"], text=True
    ).strip()
    if report["machine"]["git_sha"] != current_sha:
        raise SystemExit("report was not generated by the checked-out commit")

    expected = len(report["dataset_sizes"]) * len(report["operations"]) * args.repetitions
    results = report["results"]
    if len(results) != expected:
        raise SystemExit(f"expected {expected} raw samples, found {len(results)}")

    for result in results:
        if result["release"] != args.release:
            raise SystemExit("measurement release does not match report release")
        if result["matches_expected_digest"] is False:
            raise SystemExit(f"digest mismatch in {result['operation']}")
        if result["operation"].startswith("data-file-"):
            if result["matches_expected_digest"] is not True:
                raise SystemExit(f"missing digest result in {result['operation']}")
            if result["first_row_us"] is None:
                raise SystemExit(f"missing first-row latency in {result['operation']}")

    print(f"validated {len(results)} raw samples for {args.release}")


if __name__ == "__main__":
    main()
